---
identity:
  username: "username"
  key_file: "config/.ssh/id_rsa"

directories:
  backup_dir: "backups"
  log_dir: "logs"

settings:
  datastore_type: "yaml"
  connection_timeout: 3
  backup_max_age: 7
  log_max_age: 7
  log_max_count: 10
