name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    environment: release
    permissions:
      id-token: write
    env:
      POETRY_VIRTUALENVS_CREATE: "false"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        pipx install poetry
        pipx inject poetry poetry-bumpversion

    - name: Bump version
      run: |
        poetry version ${{ github.ref_name }}

    - name: Build package
      run: |
        poetry build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
