name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    env:
      POETRY_VIRTUALENVS_CREATE: "false"

    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: |
        pipx install poetry
        pipx inject poetry poetry-bumpversion

    - name: Bump version
      run: |
        $POETRY_HOME/bin/pip install --user poetry-bumpversion
        poetry version ${{ github.ref_name }}

    - name: Build package
      run: |
        poetry build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
